apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hybrid
  template:
    metadata:
      labels:
        app: hybrid
    spec:
      containers:
      - name: app
        image: username/devops-hybrid:latest
        ports:
        - containerPort: 3000
